### ISSUE TITLE
Dev Setup step wrong

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#1]
The second step has an error:
"run npm link reactUI in your reactUI.example directory" triggers an error: name can no longer contain capital letters
It shoud probably be npm link reactui

**Comment by maximilianweidenauer** [comment]
Yeah this step needs an update, also its probably @sibvisions/reactui because thats the name of the package but I'll have to check that out myself.

Note that linking only works if you've cloned the reactUI project. If you're using the reactUI by installing it via npm install you don't need to link!

**Comment by maximilianweidenauer** [comment]
I've changed the readme from 'npm link reactUI' to 'npm link @sibvisions/reactui'
