### ISSUE TITLE
Configure config.json

### ISSUE THREAD

**Issue by adriahuertas** [sibvisions/reactUI.example#7]
I'm not able to set up the config.json to access my project by following the README steps. What I do:

- Create config.json in reactuiexample/public/ folder
- Set up config.json: I use this URL to access the project http://localhost:3000/?language=en&appName=bricksmes&baseUrl=http%3A%2F%2Flocalhost%3A80%2Fservices%2Fmobile/#/login. So I tried to add these parameters in config.json:
{
  "appName": "bricksmes",
  "baseUrl": "http://localhost:80/services/mobile/#/login",
  "userName": "admin",
  "password": "admin",
  "langCode": "en"
}

- In the reactuiexample directory, I run "npm start".

Then, the browser opens the default http://localhost:3000/#/ URL as if config.json didn't exist.

I've tried to remove the userName and password also to pass exactly the same parameters as we do using the URL, but that didn't work either.

**Comment by maximilianweidenauer** [comment]
I've just updated the readme because it was, again, outdated but I'll explain it here anyways:

We used to always load the config.json file like described in the readme, but for quite some time now, the config.json file only gets loaded if the reactUI is running in "development" mode (you can check the mode of **your** project with process.env.NODE_ENV). When reactUI is installed via npm its always "production".

You could set it to development by linking the reactUI project again and running `npm run devbundle, but as we already discussed I wouldn't recommend linking as the npm library is sufficient.

So instead please use URL parameters instead. It is normal that when you run `npm start` you will be redirected to http://localhost:3000/#/ so after the first "/" after "3000" add a question mark and put your url parameters here.

Here is an example that I use for my demo: http://localhost:3000/?language=en&appName=demo&baseUrl=http://localhost:8080/JVx.mobile/services/mobile/#

You would have to change the "appName=demo" to "appName=bricksmes" and the baseUrl to your baseUrl. Please note, that the baseUrl **doesn't** contain the "login" nor the "#" as in your config.json. It would be just: [http://localhost:80/services/mobile](http://localhost/services/mobile/#/login)
